<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAR8J2ED\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAR8J2ED/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAR8J2ED.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAR8J2ED\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAR8J2ED\App_KernelDevDebugContainer([
    'container.build_hash' => 'AR8J2ED',
    'container.build_id' => '57f3d27c',
    'container.build_time' => 1611077293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAR8J2ED');
